# Generated by Django 3.2.3 on 2021-09-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='music_collection/static/img/hl-logo.jpg', null=True, upload_to='music_collection/my_media/profile_pic'),
        ),
    ]
