# Generated by Django 3.2.3 on 2021-09-04 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='performer',
            name='spotify',
            field=models.URLField(default='https://open.spotify.com/', max_length=60),
        ),
    ]
