# Generated by Django 3.2.3 on 2021-08-31 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicalbum',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
