# Generated by Django 3.2.3 on 2021-09-04 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musicalbum',
            name='performer',
        ),
        migrations.AddField(
            model_name='performer',
            name='performer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music.musicalbum'),
        ),
    ]
