# Generated by Django 3.2.3 on 2021-08-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='available',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Lost'), (0, 'Available'), (1, 'Borrowed')], default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(5, 'Jazz'), (8, 'R&B'), (2, 'Country'), (6, 'Metal'), (7, 'Pop'), (11, 'Rock'), (4, 'Electronic'), (12, 'Soundtrack'), (10, 'Reaggae'), (13, 'Triphop'), (1, 'Classical'), (3, 'Disco-Polo'), (0, 'Blues'), (9, 'Rap')], default=0),
        ),
    ]
