# Generated by Django 3.2.3 on 2021-08-31 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performer',
            name='albums',
            field=models.ManyToManyField(related_name='albums', to='music.MusicAlbum'),
        ),
    ]
