# Generated by Django 3.2.3 on 2021-09-04 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20210904_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performer',
            old_name='performer',
            new_name='cd_album',
        ),
    ]
