# Generated by Django 3.2.3 on 2021-08-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20210829_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='available',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Borrowed'), (2, 'Lost'), (0, 'Available')], default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Electronic'), (8, 'R&B'), (10, 'Reaggae'), (3, 'Disco-Polo'), (6, 'Metal'), (7, 'Pop'), (9, 'Rap'), (1, 'Classical'), (5, 'Jazz'), (0, 'Blues'), (13, 'Triphop'), (12, 'Soundtrack'), (11, 'Rock'), (2, 'Country')], default=0),
        ),
    ]
