# Generated by Django 3.2.3 on 2021-08-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20210825_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Blues'), (1, 'Metal'), (3, 'Jazz'), (11, 'Soundtrack'), (9, 'Rap'), (5, 'Country'), (6, 'Electronic'), (8, 'R&B'), (10, 'Reaggae'), (4, 'Classical'), (0, 'Rock'), (7, 'Pop'), (12, 'Triphop')], default=0),
        ),
    ]
