# Generated by Django 3.2.3 on 2021-08-27 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20210827_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='available',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Lost'), (0, 'Available'), (1, 'Borrowed')], default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(7, 'Pop'), (0, 'Blues'), (8, 'R&B'), (10, 'Reaggae'), (4, 'Electronic'), (3, 'Disco-Polo'), (6, 'Metal'), (2, 'Country'), (9, 'Rap'), (1, 'Classical'), (13, 'Triphop'), (12, 'Soundtrack'), (5, 'Jazz'), (11, 'Rock')], default=0),
        ),
    ]
