# Generated by Django 3.2.3 on 2021-09-04 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20210904_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicalbum',
            name='availability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music.availability'),
        ),
        migrations.RemoveField(
            model_name='musicalbum',
            name='performer',
        ),
        migrations.AddField(
            model_name='musicalbum',
            name='performer',
            field=models.ManyToManyField(max_length=64, to='music.Performer'),
        ),
    ]
