# Generated by Django 3.2.3 on 2021-09-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_musicalbum_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performer',
            name='albums',
            field=models.ManyToManyField(related_name='albums', to='music.MusicAlbum'),
        ),
    ]
