# Generated by Django 3.2.3 on 2021-08-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20210829_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='available',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Available'), (1, 'Borrowed'), (2, 'Lost')], default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Country'), (13, 'Triphop'), (12, 'Soundtrack'), (9, 'Rap'), (11, 'Rock'), (7, 'Pop'), (4, 'Electronic'), (1, 'Classical'), (6, 'Metal'), (0, 'Blues'), (10, 'Reaggae'), (8, 'R&B'), (3, 'Disco-Polo'), (5, 'Jazz')], default=0),
        ),
    ]
