# Generated by Django 3.2.3 on 2021-08-27 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_music_cover'),
        ('music', '0003_category_category'),
    ]

    operations = [
    ]
