# Generated by Django 3.2.3 on 2021-09-04 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20210904_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performer',
            name='albums',
        ),
    ]
