# Generated by Django 3.2.3 on 2021-08-27 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20210827_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Classical'), (4, 'Electronic'), (2, 'Country'), (9, 'Rap'), (0, 'Blues'), (11, 'Rock'), (8, 'R&B'), (3, 'Disco-Polo'), (10, 'Reaggae'), (5, 'Jazz'), (6, 'Metal'), (13, 'Triphop'), (12, 'Soundtrack'), (7, 'Pop')], default=0),
        ),
    ]
