# Generated by Django 3.2.3 on 2021-08-27 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_alter_category_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='available',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Borrowed'), (2, 'Lost'), (0, 'Available')], default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Electronic'), (10, 'Reaggae'), (12, 'Soundtrack'), (1, 'Classical'), (3, 'Disco-Polo'), (8, 'R&B'), (9, 'Rap'), (6, 'Metal'), (13, 'Triphop'), (2, 'Country'), (5, 'Jazz'), (7, 'Pop'), (11, 'Rock'), (0, 'Blues')], default=0),
        ),
    ]
