# Generated by Django 3.2.3 on 2021-08-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_merge_0002_music_cover_0003_category_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Classical'), (11, 'Rock'), (3, 'Disco-Polo'), (5, 'Jazz'), (2, 'Country'), (13, 'Triphop'), (8, 'R&B'), (12, 'Soundtrack'), (0, 'Blues'), (9, 'Rap'), (6, 'Metal'), (10, 'Reaggae'), (7, 'Pop'), (4, 'Electronic')], default=0),
        ),
    ]
