# Generated by Django 3.2.3 on 2021-08-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20210829_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='available',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Lost'), (0, 'Available'), (1, 'Borrowed')], default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Blues'), (11, 'Rock'), (1, 'Classical'), (2, 'Country'), (4, 'Electronic'), (10, 'Reaggae'), (9, 'Rap'), (6, 'Metal'), (3, 'Disco-Polo'), (13, 'Triphop'), (7, 'Pop'), (8, 'R&B'), (5, 'Jazz'), (12, 'Soundtrack')], default=0),
        ),
    ]
