# Generated by Django 3.2.3 on 2021-08-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20210829_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='available',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Available'), (2, 'Lost'), (1, 'Borrowed')], default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Classical'), (7, 'Pop'), (10, 'Reaggae'), (13, 'Triphop'), (6, 'Metal'), (12, 'Soundtrack'), (3, 'Disco-Polo'), (11, 'Rock'), (9, 'Rap'), (0, 'Blues'), (4, 'Electronic'), (2, 'Country'), (5, 'Jazz'), (8, 'R&B')], default=0),
        ),
    ]
