# Generated by Django 3.2.3 on 2021-08-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_alter_category_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(8, 'R&B'), (2, 'Country'), (4, 'Electronic'), (9, 'Rap'), (10, 'Reaggae'), (1, 'Classical'), (12, 'Soundtrack'), (6, 'Metal'), (0, 'Blues'), (5, 'Jazz'), (13, 'Triphop'), (11, 'Rock'), (3, 'Disco-Polo'), (7, 'Pop')], default=0),
        ),
    ]
