# Generated by Django 3.2.3 on 2021-08-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20210829_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='category_choose',
            field=models.CharField(choices=[('Bl', 'Blues'), ('Cl', 'Classical'), ('Co', 'Country'), ('D-P', 'Disco-Polo'), ('El', 'Electronic'), ('Ja', 'Jazz'), ('Me', 'Metal'), ('Po', 'Pop'), ('Rb', 'R&B'), ('Ra', 'Rap'), ('Re', 'Reaggae'), ('Ro', 'Rock'), ('So', 'Soundtrack'), ('Tr', 'Triphop')], max_length=5, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='available',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Borrowed'), (0, 'Available'), (2, 'Lost')], default=0),
        ),
    ]
