# Generated by Django 3.2.3 on 2021-08-29 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0005_auto_20210829_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='available',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Available'), (2, 'Lost'), (1, 'Borrowed')], default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Electronic'), (12, 'Soundtrack'), (9, 'Rap'), (3, 'Disco-Polo'), (8, 'R&B'), (5, 'Jazz'), (6, 'Metal'), (13, 'Triphop'), (10, 'Reaggae'), (11, 'Rock'), (7, 'Pop'), (0, 'Blues'), (2, 'Country'), (1, 'Classical')], default=0),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_me', models.TextField()),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
