# Generated by Django 3.2.3 on 2021-08-27 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20210827_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='available',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Available'), (1, 'Borrowed'), (2, 'Lost')], default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Blues'), (3, 'Disco-Polo'), (7, 'Pop'), (6, 'Metal'), (1, 'Classical'), (10, 'Reaggae'), (13, 'Triphop'), (12, 'Soundtrack'), (9, 'Rap'), (2, 'Country'), (11, 'Rock'), (8, 'R&B'), (5, 'Jazz'), (4, 'Electronic')], default=0),
        ),
    ]
