# Generated by Django 3.2.3 on 2021-08-27 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_alter_category_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.PositiveSmallIntegerField(choices=[(2, 'Lost'), (1, 'Borrowed'), (0, 'Available')], default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Electronic'), (0, 'Blues'), (6, 'Metal'), (3, 'Disco-Polo'), (13, 'Triphop'), (8, 'R&B'), (11, 'Rock'), (10, 'Reaggae'), (7, 'Pop'), (12, 'Soundtrack'), (1, 'Classical'), (9, 'Rap'), (5, 'Jazz'), (2, 'Country')], default=0),
        ),
        migrations.AddField(
            model_name='music',
            name='availability',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music.availability'),
        ),
    ]
