# Generated by Django 3.2.3 on 2021-08-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20210829_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='available',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Borrowed'), (2, 'Lost'), (0, 'Available')], default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Electronic'), (3, 'Disco-Polo'), (1, 'Classical'), (2, 'Country'), (11, 'Rock'), (5, 'Jazz'), (12, 'Soundtrack'), (13, 'Triphop'), (10, 'Reaggae'), (7, 'Pop'), (9, 'Rap'), (6, 'Metal'), (0, 'Blues'), (8, 'R&B')], default=0),
        ),
    ]
