# Generated by Django 3.2.3 on 2021-08-28 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_alter_category_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.PositiveSmallIntegerField(choices=[(0, 'Available'), (1, 'Borrowed'), (2, 'Lost')], default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(12, 'Soundtrack'), (2, 'Country'), (1, 'Classical'), (10, 'Reaggae'), (6, 'Metal'), (13, 'Triphop'), (0, 'Blues'), (5, 'Jazz'), (4, 'Electronic'), (11, 'Rock'), (9, 'Rap'), (7, 'Pop'), (3, 'Disco-Polo'), (8, 'R&B')], default=0),
        ),
        migrations.AddField(
            model_name='music',
            name='availability',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music.availability'),
        ),
    ]
