# Generated by Django 3.2.3 on 2021-08-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20210829_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='available',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Borrowed'), (2, 'Lost'), (0, 'Available')], default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_choose',
            field=models.CharField(choices=[('Blues', 'Blues'), ('Classical', 'Classical'), ('Country', 'Country'), ('Disco-Polo', 'Disco-Polo'), ('Electronic', 'Electronic'), ('Jazz', 'Jazz'), ('Metal', 'Metal'), ('Pop', 'Pop'), ('R&B', 'R&B'), ('Rap', 'Rap'), ('Reaggae', 'Reaggae'), ('Rock', 'Rock'), ('Soundtrack', 'Soundtrack'), ('Triphop', 'Triphop')], max_length=30, null=True, unique=True),
        ),
    ]
