# Generated by Django 3.2.3 on 2021-08-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20210829_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fb_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='ig_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(8, 'R&B'), (5, 'Jazz'), (12, 'Soundtrack'), (10, 'Reaggae'), (6, 'Metal'), (13, 'Triphop'), (7, 'Pop'), (2, 'Country'), (1, 'Classical'), (11, 'Rock'), (9, 'Rap'), (4, 'Electronic'), (0, 'Blues'), (3, 'Disco-Polo')], default=0),
        ),
    ]
