# Generated by Django 3.2.3 on 2021-08-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_auto_20210829_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='available',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Borrowed'), (0, 'Available'), (2, 'Lost')], default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(11, 'Rock'), (13, 'Triphop'), (3, 'Disco-Polo'), (1, 'Classical'), (2, 'Country'), (5, 'Jazz'), (0, 'Blues'), (9, 'Rap'), (8, 'R&B'), (7, 'Pop'), (10, 'Reaggae'), (4, 'Electronic'), (12, 'Soundtrack'), (6, 'Metal')], default=0),
        ),
    ]
