# Generated by Django 3.2.3 on 2021-08-28 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_auto_20210827_2158'),
        ('music', '0007_auto_20210828_1340'),
    ]

    operations = [
    ]
