# Generated by Django 3.2.3 on 2021-08-29 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_auto_20210829_1116'),
        ('music', '0007_auto_20210829_1332'),
    ]

    operations = [
    ]
