# Generated by Django 3.2.3 on 2021-08-29 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_auto_20210829_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='available',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Lost'), (0, 'Available'), (1, 'Borrowed')], default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(12, 'Soundtrack'), (5, 'Jazz'), (0, 'Blues'), (11, 'Rock'), (9, 'Rap'), (3, 'Disco-Polo'), (13, 'Triphop'), (10, 'Reaggae'), (8, 'R&B'), (1, 'Classical'), (7, 'Pop'), (2, 'Country'), (6, 'Metal'), (4, 'Electronic')], default=0),
        ),
    ]
