# Generated by Django 3.2.3 on 2021-08-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_auto_20210827_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='available',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Available'), (1, 'Borrowed'), (2, 'Lost')], default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Country'), (1, 'Classical'), (10, 'Reaggae'), (9, 'Rap'), (4, 'Electronic'), (3, 'Disco-Polo'), (0, 'Blues'), (6, 'Metal'), (11, 'Rock'), (7, 'Pop'), (5, 'Jazz'), (12, 'Soundtrack'), (8, 'R&B'), (13, 'Triphop')], default=0),
        ),
    ]
