# Generated by Django 3.2.3 on 2021-08-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_merge_0007_auto_20210829_1116_0007_auto_20210829_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='available',
        ),
        migrations.AddField(
            model_name='availability',
            name='availability_choices',
            field=models.CharField(choices=[('A', 'Available'), ('B', 'Borrowed')], max_length=1, null=True, unique=True),
        ),
    ]
