# Generated by Django 3.2.3 on 2021-08-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_auto_20210829_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='performer',
        ),
        migrations.AlterField(
            model_name='availability',
            name='availability_choices',
            field=models.CharField(choices=[('Available', 'Available'), ('Borrowed', 'Borrowed')], max_length=50, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Performer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('second_name', models.CharField(max_length=32)),
                ('albums', models.ManyToManyField(to='music.Music')),
            ],
        ),
    ]
