# Generated by Django 3.2.3 on 2021-08-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_auto_20210829_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='fb_url',
            new_name='facebook_url',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='ig_url',
            new_name='instagram_url',
        ),
        migrations.AlterField(
            model_name='availability',
            name='available',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Available'), (2, 'Lost'), (1, 'Borrowed')], default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(12, 'Soundtrack'), (6, 'Metal'), (2, 'Country'), (3, 'Disco-Polo'), (0, 'Blues'), (7, 'Pop'), (9, 'Rap'), (13, 'Triphop'), (11, 'Rock'), (1, 'Classical'), (4, 'Electronic'), (10, 'Reaggae'), (5, 'Jazz'), (8, 'R&B')], default=0),
        ),
    ]
