# Generated by Django 3.2.3 on 2021-08-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_auto_20210829_1240'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Music',
            new_name='MusicAlbum',
        ),
        migrations.AlterField(
            model_name='availability',
            name='availability_choices',
            field=models.CharField(choices=[('Available', 'Available'), ('Borrowed', 'Borrowed')], max_length=50, null=True, unique=True),
        ),
    ]
