# Generated by Django 3.2.3 on 2021-08-28 13:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_alter_category_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='available',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Borrowed'), (2, 'Lost'), (0, 'Available')], default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Reaggae'), (4, 'Electronic'), (11, 'Rock'), (7, 'Pop'), (0, 'Blues'), (13, 'Triphop'), (5, 'Jazz'), (6, 'Metal'), (9, 'Rap'), (2, 'Country'), (12, 'Soundtrack'), (3, 'Disco-Polo'), (8, 'R&B'), (1, 'Classical')], default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='stars',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
